### PR TITLE
add CustomCombinator

### PR DESCRIPTION
**Pull request by leemhenson**
Hi. I've been having another think about https://github.com/gcanti/io-ts-codegen/issues/12 and I came up with this `CustomCombinator`. What do you think?

### CODE REVIEW

**Comment by gcanti** [comment]
Looks too specific, what if you want to handle `createEitherFromJSON` (which needs two types)?

Why not mirroring `CustomTypeDeclaration`?

```ts
export interface CustomCombinator {
  kind: 'CustomCombinator'
  static: string
  runtime: string
  dependencies: Array<string> // <= this is for topological sort
}
```

For what concerns indentation I'm thinking to drop my naive formatting in favour of prettier (so no need for functions in `CustomCombinator`)

**Comment by leemhenson** [comment]
That makes sense. Done.

**Comment by gcanti** [comment]
@leemhenson thanks, looks good. Last thing, could you please add a constructor for `CustomCombinator`?

```ts
export function customCombinator(
  staticRepr: string,
  runtimeRepr: string,
  dependencies: Array<string> = []
): CustomCombinator {
  return {
    kind: 'CustomCombinator',
    static: staticRepr,
    runtime: runtimeRepr,
    dependencies
  }
}
```

**Comment by leemhenson** [comment]
😁 I originally had that in, but then took it out again because any usage of customCombinators effectively requires the user to write essentially that same function anyway. But I can see the point of providing a link in the chain where this library can introduce changes that shouldn't require the user to recompile all their customCombinators. 

So, TLDR, done.

**Comment by gcanti** [comment]
@leemhenson released in https://github.com/gcanti/io-ts-codegen/releases/tag/0.1.5

**Pull request merged**
